create table "public"."version" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "version" bigint default '0'::bigint
);


alter table "public"."version" enable row level security;

CREATE UNIQUE INDEX version_pkey ON public.version USING btree (id);

alter table "public"."version" add constraint "version_pkey" PRIMARY KEY using index "version_pkey";


